// This file has been autogenerated from a class added in the UI designer.

using System;
using Foundation;
using UIKit;

namespace ProjectDrunk.iOS
{
	public partial class ButtonCellClass : UITableViewCell
	{
        private int indexNummer;
		public ButtonCellClass (IntPtr handle) : base (handle)
		{
		}

		public void SetIndexNummer(int i)
		{
			indexNummer = i;
		}
		public int GetIndexNummer()
		{
			return indexNummer;
		}

	}
}
