// This file has been autogenerated from a class added in the UI designer.

using System;
using System.Collections.Generic;
using Foundation;
using UIKit;

namespace ProjectDrunk.iOS
{
    public partial class GameSelection : UIViewController
    {
        List<String> spelers;
        int graad;
        public GameSelection(IntPtr handle) : base(handle)
        {


        }
        public override void ViewDidLoad()
        {
            base.ViewDidLoad();


            // Perform any additional setup after loading the view, typically from a nib.
        }

        public void setSpelerData(List<String> lijst, int graad)
        {
            spelers = lijst;
            this.graad = graad;
        }

        public override void DidReceiveMemoryWarning()
        {
            base.DidReceiveMemoryWarning();

        }

		public override void PrepareForSegue(UIStoryboardSegue segue, Foundation.NSObject sender)
		{
			base.PrepareForSegue(segue, sender);
            var GameHogerLager = segue.DestinationViewController as HogerLagerViewController;
			if (GameHogerLager != null)
			{
                GameHogerLager.setSpelerData(spelers, graad);
			}
		}
    }
}
