// This file has been autogenerated from a class added in the UI designer.

using System;
using System.Collections.Generic;
using Foundation;
using ProjectDrunk.DataLaag;
using UIKit;

namespace ProjectDrunk.iOS
{
    public partial class GameSelection : UIViewController
    {
        public SpelData Data { get; private set; }

        public GameSelection(IntPtr handle) : base(handle)
        {


        }
        public override void ViewDidLoad()
        {
            base.ViewDidLoad();


            // Perform any additional setup after loading the view, typically from a nib.
        }

        public void SetSpelerData(SpelData data)
        {
            this.Data = data;
        }

        public override void DidReceiveMemoryWarning()
        {
            base.DidReceiveMemoryWarning();

        }

		public override void PrepareForSegue(UIStoryboardSegue segue, Foundation.NSObject sender)
		{
			base.PrepareForSegue(segue, sender);
            if (segue.DestinationViewController is HogerLagerViewController GameHogerLager)
            {
                GameHogerLager.SetSpelerData(Data);
            }
        }
    }
}
