// This file has been autogenerated from a class added in the UI designer.

using System;
using System.Collections.Generic;
using System.Drawing;
using Foundation;
using UIKit;

namespace ProjectDrunk.iOS
{
    public partial class HogerLagerViewController : UIViewController
    {
        List<String> spelers;
        int graad;
        HogerLager spel;

        public HogerLagerViewController(IntPtr handle) : base(handle)
        {
        }

        public override void ViewDidLoad()
        {
            base.ViewDidLoad();
            spel = new HogerLager(spelers, graad);
            werkLabelsBij();
        }

        public void werkLabelsBij(){
            SpelerNaam.Text = spel.getSpeler();
			HuidigePunten.Text = spel.getStreak().ToString();
			gokGetal.Text = spel.getGetal().ToString();
        }

        public void setSpelerData(List<String> lijst, int graad)
        {
            spelers = lijst;
            this.graad = graad;
        }

        partial void GokHoger(UIButton sender)
        {
            if (spel.GokHoger()){
				spel.nieuweSpeler();
                werkLabelsBij();
            }else{
                ShowErrorMessage();
            }

        }

        partial void GokLager(UIButton sender)
        {
            if (spel.GokLager()){
                spel.nieuweSpeler();
                werkLabelsBij();
			}
			else{
				ShowErrorMessage();
			}

        }

        public void ShowErrorMessage(){
            UIAlertView alert = new UIAlertView()
            {
                Title = spel.getSpeler(),
                Message = "Drink " + spel.getSlokken() + " keer!"
			};
			alert.AddButton("OK");
			alert.Show();
            alert.Dismissed += Alert_Dismissed;
        }

		private void Alert_Dismissed(object sender, UIButtonEventArgs e)
		{
            spel.nieuweSpeler();
			werkLabelsBij();
		}

        public override void DidReceiveMemoryWarning()
        {
            base.DidReceiveMemoryWarning();

        }
		
    }
}
