// This file has been autogenerated from a class added in the UI designer.

using System;
using System.Collections.Generic;
using System.Drawing;
using Foundation;
using ProjectDrunk.DataLaag;
using ProjectDrunk.LogischeLaag;
using UIKit;

namespace ProjectDrunk.iOS
{
    public partial class HogerLagerViewController : UIViewController
    {
        
        public HogerLager Spel { get; private set; }

        public HogerLagerViewController(IntPtr handle) : base(handle)
        {
        }

        public override void ViewDidLoad()
        {
            base.ViewDidLoad();
            WerkLabelsBij();
        }

        public void WerkLabelsBij(){
            LSpeler.Text = Spel.HuidigeSpeler.Naam;
			LPunten.Text = Spel.Streak.ToString();
			LKaart.Text = Spel.HuidigeKaart.BestandsNaam;
        }

        public void SetSpelerData(SpelData data)
        {
            Spel = new HogerLager(data);


        }

        partial void GokHoger(UIButton sender)
        {
            try
            {
                if (Spel.GokHoger())
                {
                    Spel.CorrecteGok();

                }
                else
                {
                    ShowErrorMessage();
                    Spel.FouteGok();
                }

                WerkLabelsBij();
            }
            catch (Exception)
            {

                this.NavigationController.PopViewController(true);
            }
            
        }

        partial void GokLager(UIButton sender)
        {
            try
            {
                if (Spel.GokLager())
                {
                    Spel.CorrecteGok();

                }
                else
                {
                    ShowErrorMessage();
                    Spel.FouteGok();
                }
                WerkLabelsBij();
            }
            catch (Exception)
            {

                this.NavigationController.PopViewController(true);
            }
            
        }

        public void ShowErrorMessage(){
            UIAlertView alert = new UIAlertView()
            {
                Title = Spel.HuidigeSpeler.Naam,
                Message = "Drink " + Spel.Streak + " keer!"
			};
			alert.AddButton("OK");
			alert.Show();
            alert.Dismissed += Alert_Dismissed;
        }

		private void Alert_Dismissed(object sender, UIButtonEventArgs e)
		{
            //spel.nieuweSpeler();
			//werkLabelsBij();
		}

        public override void DidReceiveMemoryWarning()
        {
            base.DidReceiveMemoryWarning();

        }
		
    }
}
