// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;

namespace ProjectDrunk.iOS
{
	public partial class TextCellClass : UITableViewCell
	{
        private int indexNummer;
		public TextCellClass (IntPtr handle) : base (handle)
		{
            //naamField.Text = "test";
		}

        public void SetIndexNummer(int i){
            indexNummer = i;
        }
		public int GetIndexNummer()
		{
            return indexNummer;
		}
        public void SetText(String s){
            naamField.Text = s;
        }
	}
}
